language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g casperjs
  - npm install -g grunt-cli
  - npm install
before_script:
  - phantomjs --version
  - casperjs --version
notifications:
  slack: uberdigital:Ces4rrJQyR0IGiBV9XCnicop